### ISSUE TITLE
Google client_id missing.

### ISSUE THREAD

**Issue by siddjellali** [calcom/docker#125]
Hello team, 

Could you please help me ? 

Please find below the error message, the docker compose and the GOOGLE variable environment;
Calendso worked from low time now and failed recently.

```
@calcom/web:start: (node:385) UnhandledPromiseRejectionWarning: HttpError: Google client_id missing.
@calcom/web:start:     at GoogleCalendarService.googleAuth (/calcom/apps/web/.next/server/chunks/8595.js:1117:36)
@calcom/web:start:     at async /calcom/apps/web/.next/server/chunks/8595.js:1310:26
@calcom/web:start: (Use `node --trace-warnings ...` to show where the warning was created)
@calcom/web:start: (node:385) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
@calcom/web:start: (node:385) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**docker-compose :** 

```
services:
  cal-postgres:
    container_name: cal-postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - database:/var/lib/postgresql/data/
    networks:
      calendso_net:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  calendso:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
        - NEXT_PUBLIC_LICENSE_CONSENT=${NEXT_PUBLIC_LICENSE_CONSENT}
        - NEXT_PUBLIC_TELEMETRY_KEY=${NEXT_PUBLIC_TELEMETRY_KEY}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    container_name: calendso
    image: calendso/calendso:latest
    restart: always
    networks:
      t2_proxy:
      calendso_net:
    environment:
      NEXT_PUBLIC_LICENSE_CONSENT: $NEXT_PUBLIC_LICENSE_CONSENT
      DATABASE_URL: $DATABASE_URL
      NEXT_PUBLIC_WEBAPP_URL: $NEXT_PUBLIC_WEBAPP_URL
      GOOGLE_API_CREDENTIALS: $GOOGLE_API_CREDENTIALS
      NEXT_PUBLIC_TELEMETRY_KEY: $NEXT_PUBLIC_TELEMETRY_KEY
      EMAIL_FROM: $EMAIL_FROM
      EMAIL_SERVER_HOST: $EMAIL_SERVER_HOST
      EMAIL_SERVER_PORT: $EMAIL_SERVER_PORT
      EMAIL_SERVER_USER: $EMAIL_SERVER_USER
      EMAIL_SERVER_PASSWORD: $EMAIL_SERVER_PASSWORD 
      CALENDSO_ENCRYPTION_KEY: $CALENDSO_ENCRYPTION_KEY
      NODE_ENV: $NODE_ENV
      NEXT_PUBLIC_WEBSITE_URL: $NEXT_PUBLIC_WEBSITE_URL
      NEXT_PUBLIC_EMBED_LIB_URL: $NEXT_PUBLIC_EMBED_LIB_URL
      NEXTAUTH_URL: $NEXTAUTH_URL
      NEXTAUTH_SECRET: $NEXTAUTH_SECRET
    depends_on:
      cal-postgres:
        condition: service_healthy
      
volumes:
  database:
    driver: local

```

**GOOGLE_API_CREDENTIALS** = {"web":{"client_id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","project_id":"calendso-338110","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","redirect_uris":["https://agenda.xxxxxxxxxxxxxx.com/api/integrations/googlecalendar/callback"],"javascript_origins":["https://agenda.xxxxxxxxx.com"]}}
