### ISSUE TITLE
localhost:3000 everywhere

### ISSUE THREAD

**Issue by siddjellali** [calcom/docker#136]
Hello team, 

Could you please help me on that ?

![image](https://user-images.githubusercontent.com/3965823/177962214-4dc733a7-cce4-4910-85e1-17ed9e4b4d0b.png)

> Docker compose 
```
  calendso:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
        - NEXT_PUBLIC_LICENSE_CONSENT=${NEXT_PUBLIC_LICENSE_CONSENT}
        - NEXT_PUBLIC_TELEMETRY_KEY=${NEXT_PUBLIC_TELEMETRY_KEY}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - BASE_URL=${BASE_URL}
    container_name: calendso
    image: calendso/calendso:latest
    restart: always
    environment:
      NEXT_PUBLIC_LICENSE_CONSENT: $NEXT_PUBLIC_LICENSE_CONSENT
      DATABASE_URL: $DATABASE_URL
      NEXT_PUBLIC_WEBAPP_URL: $NEXT_PUBLIC_WEBAPP_URL
      GOOGLE_API_CREDENTIALS: $GOOGLE_API_CREDENTIALS
      NEXT_PUBLIC_TELEMETRY_KEY: $NEXT_PUBLIC_TELEMETRY_KEY
      EMAIL_FROM: $EMAIL_FROM
      EMAIL_SERVER_HOST: $EMAIL_SERVER_HOST
      EMAIL_SERVER_PORT: $EMAIL_SERVER_PORT
      EMAIL_SERVER_USER: $EMAIL_SERVER_USER
      EMAIL_SERVER_PASSWORD: $EMAIL_SERVER_PASSWORD 
      CALENDSO_ENCRYPTION_KEY: $CALENDSO_ENCRYPTION_KEY
      NODE_ENV: $NODE_ENV
      NEXT_PUBLIC_WEBSITE_URL: $NEXT_PUBLIC_WEBSITE_URL
      NEXT_PUBLIC_EMBED_LIB_URL: $NEXT_PUBLIC_EMBED_LIB_URL
      NEXTAUTH_URL: $NEXTAUTH_URL
      NEXTAUTH_SECRET: $NEXTAUTH_SECRET
      BASE_URL: $BASE_URL
      DOCKER_BUILDKIT: 0
```

I have all these variables configured in calcom docker 

BASE_URL : https://agenda.xxxxxxx.com
NEXTAUTH_URL: https://agenda.xxxxxxx.com
NEXT_PUBLIC_APP_URL: https://agenda.xxxxxxx.com
NEXT_PUBLIC_WEBSITE_URL: https://agenda.xxxxxxx.com
NEXT_PUBLIC_WEBAPP_URL: https://agenda.xxxxxxx.com

What do i miss ?

![image](https://user-images.githubusercontent.com/3965823/177962855-960be65b-b195-4a2a-bfb4-f84c906fef19.png)

+yellow: the license banner that won't go away (NEXT_PUBLIC_LICENSE_CONSENT: agree)

Thanks a lot for your support.
