### ISSUE TITLE
Telemetry can't be disabled because of typo in `docker-compose.yaml`

### ISSUE THREAD

**Issue by bdeak4** [calcom/docker#165]
While testing self-hosted docker installation I saw interesting warning so I decided to investigate further.
```
[Warning] One or more build-args [CALCOM_TELEMETRY_DISABLE] were not consumed
```

In [docker-compose.yaml](https://github.com/calcom/docker/blob/main/docker-compose.yaml#L30) there is argument declaration for this variable and it has a typo:

```yml
services:
  # ...
  calcom:
    build:
      # ...
      args:
        # ...
        CALCOM_TELEMETRY_DISABLE: ${CALCOM_TELEMETRY_DISABLED}
```

argument assigned here is `CALCOM_TELEMETRY_DISABLE` but argument used in [Dockerfile](https://github.com/calcom/docker/blob/main/Dockerfile#L16) is `CALCOM_TELEMETRY_DISABLED`.

```Dockerfile
ARG CALCOM_TELEMETRY_DISABLED
```

I plan to create PR that addresses this issue shortly. (Edit: PR #166 created)
