### ISSUE TITLE
issue with installing

### ISSUE THREAD

**Issue by killmasta93** [calcom/docker#182]
Hi Currently trying to install with docker but im getting issue altering running these steps

```
Clone calcom/docker

git clone https://github.com/calcom/docker.git

Change into the directory

cd docker


cp .env.example .env


docker compose up -d 
```

the env
```

# Set this value to 'agree' to accept our license:
# LICENSE: https://github.com/calendso/calendso/blob/main/LICENSE
#
# Summary of terms:
# - The codebase has to stay open source, whether it was modified or not
# - You can not repackage or sell the codebase
# - Acquire a commercial license to remove these terms by emailing: license@cal.com
NEXT_PUBLIC_LICENSE_CONSENT=
LICENSE=

# BASE_URL and NEXT_PUBLIC_APP_URL are both deprecated. Both are replaced with one variable, NEXT_PUBLIC_WEBAPP_URL
# BASE_URL=http://localhost:3000
# NEXT_PUBLIC_APP_URL=http://localhost:3000

NEXT_PUBLIC_WEBAPP_URL=http://localhost:3000

# Configure NEXTAUTH_URL manually if needed, otherwise it will resolve to {NEXT_PUBLIC_WEBAPP_URL}/api/auth
# NEXTAUTH_URL=http://localhost:3000/api/auth

# It is highly recommended that the NEXTAUTH_SECRET must be overridden and very unique
# Use `openssl rand -base64 32` to generate a key
NEXTAUTH_SECRET=secret

# Encryption key that will be used to encrypt CalDAV credentials, choose a random string, for example with `dd if=/dev/urandom bs=1K count=1 | md5sum`
CALENDSO_ENCRYPTION_KEY=secret

# Deprecation note: JWT_SECRET is no longer used
# JWT_SECRET=secret

POSTGRES_USER=unicorn_user
POSTGRES_PASSWORD=magical_password
POSTGRES_DB=calendso
DATABASE_HOST=database:5432
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
GOOGLE_API_CREDENTIALS={}

# Set this to '1' if you don't want Cal to collect anonymous usage
CALCOM_TELEMETRY_DISABLED=

# Used for the Office 365 / Outlook.com Calendar integration
MS_GRAPH_CLIENT_ID=
MS_GRAPH_CLIENT_SECRET=

# Used for the Zoom integration
ZOOM_CLIENT_ID=
ZOOM_CLIENT_SECRET=

# E-mail settings
# Configures the global From: header whilst sending emails.
EMAIL_FROM=xxxxx

# Configure SMTP settings (@see https://nodemailer.com/smtp/).
EMAIL_SERVER_HOST=xxxxxx
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER=xxxx
EMAIL_SERVER_PASSWORD=xxxxx

NODE_ENV=production
```

```
# Use postgres/example user/password credentials
version: '3.8'

volumes:
  database-data:

networks:
  stack:
    name: stack
    external: false

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - stack

  calcom:
    image: calendso/calendso:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBAPP_URL: ${NEXT_PUBLIC_WEBAPP_URL}
        NEXT_PUBLIC_LICENSE_CONSENT: ${NEXT_PUBLIC_LICENSE_CONSENT}
        CALCOM_TELEMETRY_DISABLED: ${CALCOM_TELEMETRY_DISABLED}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
        DATABASE_URL: ${DATABASE_URL}
      network: stack
    restart: always
    networks:
      - stack
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - database
```

```
@calcom/web:build: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
@calcom/web:build: https://nextjs.org/telemetry
@calcom/web:build: 
@calcom/web:build: info  - Linting and checking validity of types...
@calcom/web:build: info  - Creating an optimized production build...
@calcom/web:build: warn  - You are using an experimental edge runtime, the API might change.
@calcom/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (176kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
@calcom/web:build: Failed to compile.
@calcom/web:build: 
@calcom/web:build: ../../packages/features/ee/common/components/LicenseRequired.tsx
@calcom/web:build: Module not found: Can't resolve 'dompurify' in '/calcom/packages/features/ee/common/components'
@calcom/web:build: 
@calcom/web:build: Import trace for requested module:
@calcom/web:build: ../../packages/features/ee/common/components/LicenseRequired.tsx
@calcom/web:build: 
@calcom/web:build: ../../packages/features/ee/common/components/v2/LicenseRequired.tsx
@calcom/web:build: Module not found: Can't resolve 'dompurify' in '/calcom/packages/features/ee/common/components/v2'
@calcom/web:build: 
@calcom/web:build: Import trace for requested module:
@calcom/web:build: ../../packages/features/ee/common/components/v2/LicenseRequired.tsx
@calcom/web:build: 
@calcom/web:build: 
@calcom/web:build: > Build failed because of webpack errors
@calcom/web:build: error Command failed with exit code 1.
@calcom/web:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/web:build: ERROR: command finished with error: command (apps/web) yarn run build exited (1)
command (apps/web) yarn run build exited (1)

 Tasks:    7 successful, 8 total
Cached:    0 cached, 8 total
  Time:    7m19.232s 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn turbo run build --filter=@calcom/web' returned a non-zero code: 1
ERROR: Service 'calcom' failed to build : Build failed

```
