### ISSUE TITLE
Build API & Swagger as well

### ISSUE THREAD

**Issue by berts83231** [calcom/docker#270]
I use both Swagger and the api for our hosted service.

It would make sense to build these additional services at the same time.
And run them by modifying docker-compose.

```
  api:
    container_name: cal-api
    image: calcom.docker.scarf.sh/calcom/cal.com
    restart: always
    networks:
      - stack
    ports:
      - 3002:3002
    env_file: .env
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - database
    working_dir: /calcom/apps/api
    command: npx next start

  swagger:
    container_name: cal-swagger
    image: calcom.docker.scarf.sh/calcom/cal.com
    restart: always
    networks:
      - stack
    ports:
      - 4200:4200
    env_file: .env
    environment:
      - PORT=4200
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - database
    working_dir: /calcom/apps/swagger
    command: npx next dev
```
