### ISSUE TITLE
SECRET issue

### ISSUE THREAD

**Issue by 7aklhz** [calcom/docker#88]
Hi, 

I have installed calcom using Docker and when I open my app url, I get errors concerning missing secret
`[next-auth][error][NO_SECRET]
2022-02-22T16:26:01.391583752Z https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.
2022-02-22T16:26:01.391591995Z at assertConfig (/calcom/node_modules/next-auth/core/lib/assert.js:24:14)
2022-02-22T16:26:01.391598403Z at NextAuthHandler (/calcom/node_modules/next-auth/core/index.js:34:52)
2022-02-22T16:26:01.391602445Z at NextAuthNextHandler (/calcom/node_modules/next-auth/next/index.js:20:51)
2022-02-22T16:26:01.391606251Z at /calcom/node_modules/next-auth/next/index.js:56:38
2022-02-22T16:26:01.391609921Z at Object.apiResolver (/calcom/node_modules/next/dist/server/api-utils.js:101:15)
2022-02-22T16:26:01.391613598Z at runMicrotasks (<anonymous>)
2022-02-22T16:26:01.391617710Z at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-02-22T16:26:01.391621376Z at async NextNodeServer.runApi (/calcom/node_modules/next/dist/server/next-server.js:319:9)
2022-02-22T16:26:01.391625003Z at async Object.fn (/calcom/node_modules/next/dist/server/base-server.js:486:37)
2022-02-22T16:26:01.391628618Z at async Router.execute (/calcom/node_modules/next/dist/server/router.js:228:32) {
2022-02-22T16:26:01.391632681Z code: 'NO_SECRET'`

I tried adding ' NEXTAUTH_SECRET' in env variables but it did not work.

Any ideas ?

**Comment by drestrepob** [comment]
Where you able to get this fixed?

**Comment by alonsomoya** [comment]
I faced the same, and managed to fix it by adding all envars from https://github.com/calcom/cal.com/blob/main/.env.example
```
      - env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: XXXX
        - name: POSTGRES_DB
          value: calendso
        - name: DATABASE_HOST
          value: postgres-postgresql.postgres.svc.cluster.local:5432
        - name: DATABASE_URL
          value: postgresql://postgres:XXXX@postgres-postgresql.postgres.svc.cluster.local:5432
        - name: BASE_URL
          value: http://localhost:3000
        - name: NEXT_PUBLIC_WEBAPP_URL
          value: http://localhost:3000
        - name: NEXT_PUBLIC_APP_URL
          value: http://localhost:3000
        - name: NEXTAUTH_URL
          value: http://localhost:3000
        - name: NEXT_PUBLIC_LICENSE_CONSENT
        - name: LICENSE
        - name: NODE_ENV
          value: production
        - name: MS_GRAPH_CLIENT_ID
        - name: MS_GRAPH_CLIENT_SECRET
        - name: ZOOM_CLIENT_ID
        - name: ZOOM_CLIENT_SECRET
        - name: SAML_DATABASE_URL
        - name: SAML_ADMINS
        - name: PGSSLMODE
        - name: JWT_SECRET
          value: secret
        - name: NEXTAUTH_COOKIE_DOMAIN
          value: .example.com
        - name: CALENDSO_ENCRYPTION_KEY
        - name: NEXT_PUBLIC_INTERCOM_APP_ID
        - name: NEXT_PUBLIC_ZENDESK_KEY
        - name: NEXT_PUBLIC_HELPSCOUT_KEY
        - name: NEXT_PUBLIC_IS_E2E
        - name: EMAIL_FROM
          value: mail@example.com

```
