### ISSUE TITLE
Unable to follow README instructions as submodules are private

### ISSUE THREAD

**Issue by riceo** [calcom/docker#96]
I'm attempting to evaluate Cal locally on my machine via Docker compose. I followed the readme on the homepage of this repo but found the `submodule init` step fails due to missing submodules which I assume are private repos:

*  https://github.com/calcom/api
* https://github.com/calcom/website

How do I get around this? Is there a preferred way to evaluate Cal or some documentation I am missing?

Thanks

**Comment by riceo** [comment]
I just modified `docker-compose.yaml` to pull the official image instead of building it locally:

```
  calendso:
    image: calendso/calendso:latest
    restart: always
    networks:
      - stack
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - database
```

This allows the `docker-compose up` to run but if the repos *are* meant to be private:

1. You'll want to update the readme on this repo to reflect that it won't work out of the box
2. The private repos are now being leaked in the built docker images at https://hub.docker.com/r/calendso/calendso
